export const flags = {
  INITIAL_VALUE: 'THEATRE-BOOKING/FLAGS/INITIAL_VALUE',
  ERROR: 'THEATRE-BOOKING/FLAGS/ERROR',
  NOT_FOUND: 'THEATRE-BOOKING/FLAGS/NOT_FOUND'
};

export const admin = {
  AUTHENTICATE: 'THEATRE-BOOKING/ADMIN/AUTHENTICATE',
  LOGOUT: 'THEATRE-BOOKING/ADMIN/LOGOUT',

  VERIFY_SESSION: 'THEATRE-BOOKING/ADMIN/VERIFY_SESSION',
  VERIFY_SESSION_SUCCESSFUL: 'THEATRE-BOOKING/ADMIN/VERIFY_SESSION_SUCCESSFUL',
  VERIFY_SESSION_FAILED: 'THEATRE-BOOKING/ADMIN/VERIFY_SESSION_FAILED',
};

export const user = {
  AUTHENTICATE: 'THEATRE-BOOKING/USER/AUTHENTICATE',
  LOGOUT: 'THEATRE-BOOKING/USER/LOGOUT',

  ADD_TO_CART: 'THEATRE-BOOKING/USER/ADD_TO_CART',

  VERIFY_SESSION: 'THEATRE-BOOKING/USER/VERIFY_SESSION',
  VERIFY_SESSION_SUCCESSFUL: 'THEATRE-BOOKING/USER/VERIFY_SESSION_SUCCESSFUL',
  VERIFY_SESSION_FAILED: 'THEATRE-BOOKING/USER/VERIFY_SESSION_FAILED',
};